// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOghUnn908KEbdqvxwRGG3g3r9Uvr_BIo',
    appId: '1:211066895152:web:23e6ba219e7437cd50e6f5',
    messagingSenderId: '211066895152',
    projectId: 'todo-list-route-as',
    authDomain: 'todo-list-route-as.firebaseapp.com',
    storageBucket: 'todo-list-route-as.appspot.com',
    measurementId: 'G-Z1X5YR8B37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD_MY_GkWUAwRi_rVvXH3-J9RMBEq4uzQ',
    appId: '1:211066895152:android:3e25e919d7470c5650e6f5',
    messagingSenderId: '211066895152',
    projectId: 'todo-list-route-as',
    storageBucket: 'todo-list-route-as.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAKI0Mgh1QfzxjLxArYs2uoVWy07jJ8A',
    appId: '1:211066895152:ios:68e80f372d385edd50e6f5',
    messagingSenderId: '211066895152',
    projectId: 'todo-list-route-as',
    storageBucket: 'todo-list-route-as.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaAKI0Mgh1QfzxjLxArYs2uoVWy07jJ8A',
    appId: '1:211066895152:ios:25729836874fcf2450e6f5',
    messagingSenderId: '211066895152',
    projectId: 'todo-list-route-as',
    storageBucket: 'todo-list-route-as.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
